const packName = document.getElementById("packName");
const itemName = document.getElementById("itemName");
const identifier = document.getElementById("identifier");

const textureFile = document.getElementById("textureFile");

const previewImage = document.getElementById("previewImage");
const previewText = document.getElementById("previewText");

const output = document.getElementById("output");

const uuidButton = document.getElementById("generateUUID");
const addonButton = document.getElementById("generateAddon");

let behaviorUUID = "";
let resourceUUID = "";

let textureData = null;
let textureName = "";

function log(text){

    output.value += text + "\n";
    output.scrollTop = output.scrollHeight;

}

function randomHex(length){

    const chars="0123456789abcdef";

    let result="";

    for(let i=0;i<length;i++){

        result+=chars[Math.floor(Math.random()*chars.length)];

    }

    return result;

}

function generateUUID(){

    return(

        randomHex(8)+"-"+

        randomHex(4)+"-"+

        "4"+randomHex(3)+"-"+

        "8"+randomHex(3)+"-"+

        randomHex(12)

    );

}

textureFile.addEventListener("change",()=>{

    const file=textureFile.files[0];

    if(!file)return;

    textureName=file.name.replace(".png","");

    const reader=new FileReader();

    reader.onload=e=>{

        textureData=e.target.result;

        previewImage.src=textureData;

        previewImage.style.display="block";

        previewText.textContent=file.name;

        log("✔ PNG Loaded");

    };

    reader.readAsDataURL(file);

});

uuidButton.onclick=()=>{

    behaviorUUID=generateUUID();

    resourceUUID=generateUUID();

    output.value="";

    log("✔ UUID Generated");
    log("");

    log("Behavior Pack");
    log(behaviorUUID);

    log("");

    log("Resource Pack");
    log(resourceUUID);

};

addonButton.onclick=async()=>{

    output.value="";

    if(packName.value===""){

        log("❌ Pack Name required");
        return;

    }

    if(itemName.value===""){

        log("❌ Item Name required");
        return;

    }

    if(identifier.value===""){

        log("❌ Identifier required");
        return;

    }

    if(textureData===null){

        log("❌ PNG required");
        return;

    }

    if(behaviorUUID===""){

        behaviorUUID=generateUUID();

        resourceUUID=generateUUID();

    }

    log("✔ Creating Project...");

    const zip=new JSZip();

    const BP=zip.folder(packName.value+"_BP");

    const RP=zip.folder(packName.value+"_RP");

    log("✔ Behavior Pack");

    log("✔ Resource Pack");

    const bpManifest={

        format_version:2,

        header:{

            name:packName.value,

            description:"Generated by PA Addon Studio",

            uuid:behaviorUUID,

            version:[1,0,0],

            min_engine_version:[1,21,0]

        },

        modules:[

            {

                type:"data",

                uuid:generateUUID(),

                version:[1,0,0]

            }

        ]

    };

    const rpManifest={

        format_version:2,

        header:{

            name:packName.value,

            description:"Generated by PA Addon Studio",

            uuid:resourceUUID,

            version:[1,0,0],

            min_engine_version:[1,21,0]

        },

        modules:[

            {

                type:"resources",

                uuid:generateUUID(),

                version:[1,0,0]

            }

        ]

    };

    BP.file(

        "manifest.json",

        JSON.stringify(bpManifest,null,4)

    );

    RP.file(

        "manifest.json",

        JSON.stringify(rpManifest,null,4)

    );

    log("✔ manifest.json");

    const itemFolder=

        BP.folder("items");

    const textureFolder=

        RP.folder("textures").folder("items");

    const textureJsonFolder=

        RP.folder("textures");

    const langFolder=

        RP.folder("texts");
            const itemJson = {

        "format_version": "1.21.0",

        "minecraft:item": {

            "description": {

                "identifier": identifier.value,

                "menu_category": {

                    "category": "items"

                }

            },

            "components": {

                "minecraft:icon": textureName,

                "minecraft:display_name": {

                    "value": itemName.value

                }

            }

        }

    };

    itemFolder.file(

        textureName + ".json",

        JSON.stringify(itemJson, null, 4)

    );

    log("✔ item.json");

    const itemTexture = {

        "resource_pack_name": "vanilla",

        "texture_name": "atlas.items",

        "texture_data": {}

    };

    itemTexture.texture_data[textureName] = {

        "textures": "textures/items/" + textureName

    };

    RP.file(

        "textures/item_texture.json",

        JSON.stringify(itemTexture, null, 4)

    );

    log("✔ item_texture.json");

    RP.file(

        "texts/en_US.lang",

        "item." +
        identifier.value.replace(":",".") +
        ".name=" +
        itemName.value

    );

    RP.file(

        "texts/languages.json",

        JSON.stringify([
            "en_US"
        ], null, 4)

    );

    log("✔ Language Files");

    const base64 = textureData.split(",")[1];

    textureFolder.file(

        textureName + ".png",

        base64,

        {

            base64: true

        }

    );

    log("✔ Texture");

    const addonBlob = await zip.generateAsync({

        type:"blob"

    });

    const url = URL.createObjectURL(addonBlob);

    const a = document.createElement("a");

    a.href = url;

    a.download = packName.value + ".mcaddon";

    document.body.appendChild(a);

    a.click();

    a.remove();

    URL.revokeObjectURL(url);

    log("");

    log("✅ Add-on Created Successfully");

};